### PR TITLE
Add 7.1 into the documentation

### PR DESCRIPTION
**Pull request by brianwulbern**

### CODE REVIEW

**Comment by jhinkey** [comment]
Hey @brianwulbern,

Sorry I didn't send you my branch https://github.com/jhinkey/liferay-docs/tree/71-understanding-the-app-review-process. 

I'll copy and commit your changes to it. Thanks!

**Comment by jhinkey** [comment]
Thanks, @brianwulbern . I sent your changes in https://github.com/sez11a/liferay-docs/pull/3629

**Comment by brianwulbern** [comment]
Thanks @jhinkey!

**Comment by brianwulbern** [comment]
I need to send another update about our testing environments, changing, Win 7 --> Win 10.  I'll send to the liferay user and link here

**Comment by brianwulbern** [comment]
https://github.com/liferay/liferay-docs/pull/453

**Pull request closed without merging**
