### PR TITLE
Add specific reference to ViewPortletProvider class

### PR DESCRIPTION
**Pull request by phelgren**
Clarifies where to put the property since the @Component directive is in both Java files

### CODE REVIEW

**Comment by codyhoag** [comment]
@phelgren when you say "both Java files", which ones are you referring to? I'd be happy to merge this in but I want to first understand the confusion. We're only editing one Java class throughout this tutorial. Thanks!

**Comment by phelgren** [comment]
That is the confusing part of the tutorial....The tutorial really only 
"talks" about one file and yet the example that it points to has TWO! 
(actually 4 if you included the two under 'constants') So, yeah, my 
question is, since the tutorial mish-mashed references of the two files 
into one tutorial (a portlet class and a class that implements 
ViewPortletProvider) the snippet for the property= 
{"service.ranking:Integer=10"} is kind of orphaned.  The context of the 
snippet is lost and it took me a while to figure out where it should 
go.  It just needs to be more explicit which is why the reference to the 
"class that implements ViewPortletProvider" anchors the context for the 
reader (IMHO)

Pete Helgren
www.petesworkshop.com
GIAC Secure Software Programmer-Java
Twitter - Sys_i_Geek  IBM_i_Geek

**Comment by codyhoag** [comment]
Thanks for the feedback. The entire article was only meant to focus on the `ViewPortletProvider` class. I see the possible confusion if you take a look at the example and see that more classes are contained there. We're only interested in pointing to a portlet class from the `ViewPortletProvider` and nothing more. We'll make sure this is made more obvious.

**Comment by sez11a** [comment]
Superseded by https://github.com/sez11a/liferay-docs/pull/2610

**Pull request closed without merging**
