### PR TITLE
Update 02-integrating-persistence-framework.markdown

### PR DESCRIPTION
**Pull request by pandaboi**
adjust Uuid setter of guestbook because it won't compile otherwise

### CODE REVIEW

**Comment by sez11a** [comment]
@codyhoag or @ngaskill or @rbohl : can you review?

**Comment by codyhoag** [comment]
I'll test this later today

**Comment by codyhoag** [comment]
@pandaboi the original `guestbook.setUuid(serviceContext.getUuid());` should work because it is calling the [GuestbookModel.setUuid(String)](https://github.com/liferay/liferay-docs/blob/6.2.x/develop/learning-paths/mvc/code/learning-sdk/portlets/guestbook-portlet/docroot/WEB-INF/service/com/liferay/docs/guestbook/model/GuestbookModel.java#L75). Does your `GuestbookModel` class not have that method after you've built your services?

**Comment by pandaboi** [comment]
@codyhoag The `GuestbookModel` did not have the `GuestbookModel#setUuid()` method. After some investigation I figured out that the `Guestbook`-Entity (in `service.xml`) does not have the 'Uuid'-checkbox checked. I'll think this step is missing in the `USING SERVICE BUILDER TO GENERATE A PERSISTENCE FRAMEWORK` tutorial, am I right?

**Comment by codyhoag** [comment]
@pandaboi you're right. The Uuid was not getting set to `true` in the `service.xml` which meant you were unable to call `setUuid`. I've sent a fix: sez11a#1592

**Pull request closed without merging**
