### PR TITLE
Update 03-upgrading-liferay.markdown

### PR DESCRIPTION
**Pull request by arundaskd**
Without the jar files from tomcat bin folder, not able to do an successful db_upgrade.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
I had the same problem and solved it with a similar change.
@sammonsjl please merge it

**Comment by sammonsjl** [comment]
I don't have merge rights on this repo.  @codyhoag is this something you can help with?

**Comment by codyhoag** [comment]
@sez11a has the merge rights for this repo...

Rich, looks good from my end. Since we have @jorgediaz-lr 's confirmation, I think it's good to merge. :smile:

**Comment by sez11a** [comment]
Merged; thanks guys!

**Pull request merged**
