### PR TITLE
I think it would be good to include a reference to original Clay documentation

### PR DESCRIPTION
**Pull request by kgolebiowski**

### CODE REVIEW

**Comment by sez11a** [comment]
@mwilliams2014 Please confirm.

**Comment by mwilliams2014** [comment]
@sez11a , yeah I think that's fine. We should just make it clear that the link is to the Clay Icon component, so there is no confusion that you can use it in the taglib/ JSP/ FreeMarker this way. I'll send a minor edit in a bit to rename the link to `Clay Icon Component`

**Comment by mwilliams2014** [comment]
Sent https://github.com/sez11a/liferay-docs/pull/4703 @kgolebiowski  Clay UI V2 is the best option for 7.1. While it may be possible to get Clay UI 3.x.x (the docs you linked to) to work in 7.1, it's not tested for 7.1, so you may run into issues. So, I've updated the link to point to Clay UI V2 docs. Thanks for the suggestion! I think it is good to link to those so people are aware that they can use Clay icons as components in their JS too.

**Comment by sez11a** [comment]
Superseded by https://github.com/sez11a/liferay-docs/pull/4703. Thank you, @kgolebiowski and @mwilliams2014 !

**Pull request closed without merging**
