### PR TITLE
Update 08-compiling-sass-files-in-a-maven-project.markdown

### PR DESCRIPTION
**Pull request by david-truong**
We had some issues with the original version when a sass file included buorbon

### CODE REVIEW

**Comment by codyhoag** [comment]
@david-truong could you explain how the newly added `maven-dependency-plugin` is being used, and why it's necessary? I'll need to provide an explanation for this so readers know what this updated snippet accomplishes. Thanks!

**Comment by david-truong** [comment]
maybe we should leave the old way and the new way.  Basically we are using the plugin to download a jar and that jar is being passed into CSS builder.  The jar is nothing but a bunch of sass libraries.  You could also point to a directory if you wish... but that's not very portable.

**Comment by codyhoag** [comment]
@david-truong would it be accurate to say that the new `maven-dependency-plugin` is necessary **only** for developers using Buorbon in their Sass files? We can instruct people to add the extra dependency if using Buorbon, and skip it if they're not. Does that sound good?

**Comment by codyhoag** [comment]
Sent sez11a#1930. Thanks!

**Pull request merged**
