### PR TITLE
Correct filename

### PR DESCRIPTION
**Pull request by brett-shelton**
Correct filename and note that there can be no extra spaces on any line.

### CODE REVIEW

**Comment by jhinkey** [comment]
@brett-shelton 

Thanks for the correction on the filename. I mentioned your issue with the extra spaces and trailing whitespace. We've not been able to reproduce the issue. 

In a comment, would you add your .cfg file content?

Thanks again,
Jim

**Comment by brett-shelton** [comment]
```blacklistBundleSymbolicNames=\
Liferay Marketplace,\
com.liferay.marketplace,\
com.liferay.marketplace.app.manager.web,\
com.liferay.marketplace.deployer,\
com.liferay.marketplace.service,\
com.liferay.marketplace.store.web,\
Liferay Sharepoint Connector,\
Liferay Sharepoint Connector-sharepoint-hook-wrapper,\
sharepoint-hook,\
documentum-hook,\
Liferay Documentum Connector-documentum-hook-wrapper```

**Comment by jhinkey** [comment]
Thanks, Brett. Our team is taking a look at it.

**Comment by jhinkey** [comment]
Brett, 

We didn't have any problems processing that black list. Can you describe the problem you're experiencing?

Also, when you blacklist an LPKG (Liferay Marketplace), you don't need to blacklist the internal modules since uninstalling an LPKG uninstalls its internal modules.

Thanks

**Comment by brett-shelton** [comment]
That blacklist works if there is no extra whitespace characters.

**Comment by jhinkey** [comment]
Brett,

I was able to reproduce the problem with the whitespaces. I'll submit your changes. Thank you.

**Comment by jhinkey** [comment]
Sent via https://github.com/sez11a/liferay-docs/pull/2626

**Comment by jhinkey** [comment]
Brett - I filed this bug for the blacklisting behavior: https://issues.liferay.com/browse/LPS-75494

**Pull request closed without merging**
