### PR TITLE
Liferay 7 basic portlet

### PR DESCRIPTION
**Pull request by wman**
not sure where to put this, but here's a start to documenting liferay 7 development ... (very rough draft)

### CODE REVIEW

**Comment by codyhoag** [comment]
Thanks, Wilson! The steps and info you've provided are really great. I'll need to check with Ray to see if this is the way we'd like to document creating an OSGi portlet for Liferay 7.0 using the SDK. This is useful info for the way it is now, even if this isn't the permanent way of doing it. I'll keep you up-to-date on how we move forward. Thanks, again!

**Comment by wman** [comment]
hey Cody, just an FYI, i've added more documentation in the GS wiki since i sent this PR: https://in.liferay.com/web/global-services/wiki/-/wiki/Knowledge+Base/Liferay+7

**Comment by codyhoag** [comment]
Excellent! Thanks for letting me know.

**Comment by sez11a** [comment]
@wman and @codyhoag Should this PR be closed?

**Comment by codyhoag** [comment]
Yeah, this can be closed. We've extracted bits and pieces out of this document and sprinkled it throughout our tutorials. Thanks again @wman for this tutorial and the many others in the GS wiki!

**Comment by wman** [comment]
@codyhoag no problem, glad we were able to contribute a bit.  I will close this PR.  thanks!

**Pull request closed without merging**
