### PR TITLE
Update 02-integrating-persistence-framework.markdown

### PR DESCRIPTION
**Pull request by cehjohnson**
What was there earlier did not compile for me. The solution was proposed here:
https://www.liferay.com/community/forums/-/message_boards/view_message/54808806#_19_message_54772697

### CODE REVIEW

**Comment by sez11a** [comment]
Thanks for your pull. This, however, would break the existing code. I think what happened is that in an edit, the method for a future state of the portlet was placed into the documentation. The correct fix would be simply to remove the line of code that sets the UUID, as it's not needed yet at this stage of the portlet.

**Comment by cehjohnson** [comment]
>>This, however, would break the existing code
Sorry - i don't follow. *How* would it?

**Comment by sez11a** [comment]
You'd be unnecessarily incrementing the entryId twice, causing holes in the database. Not a huge issue, but not one that we want to have in our docs. :)

**Comment by cehjohnson** [comment]
OK - so you're saying that the entryId is already being set automatically by the framework?

**Comment by sez11a** [comment]
Exactly. When you write these two lines: 

		long entryId = counterLocalService.increment();
		
		Entry entry = entryPersistence.create(entryId);

You get a new entryId from the counter and then you create an Entry with the ID that you got. Because of that, you never need to set the entryId; it's already set by the constructor when you created it.

**Comment by cehjohnson** [comment]
OK then as you said before - the correct solution is to allow that ctor to do its work? If so, i wonder why/how in later iterations a uuid is being set explicitly?

**Comment by sez11a** [comment]
Because the entry's UUID and its entryId are not the same thing. They're two different fields, with values generated differently. The entryId is just the primary key for the database. The UUID (http://en.wikipedia.org/wiki/Universally_unique_identifier) is meant to be unique across databases. That's why it's implemented later: it's needed for things like DataHandlers (LAR files, staging). 

In the Learning Paths, we try to keep things simple at first and tack on more advanced concepts later. :-)

**Comment by cehjohnson** [comment]
>The UUID (http://en.wikipedia.org/wiki/Universally_unique_identifier) is meant to be unique across databases. 

Ok - got it

**Pull request closed without merging**
