### PR TITLE
Update 00-lexicon-and-themes-intro.markdown

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by mwilliams2014** [comment]
reviewing now. Thx!

**Comment by mwilliams2014** [comment]
Sent https://github.com/sez11a/liferay-docs/pull/2539

**Comment by blzaugg** [comment]
@marcoscv-work, I was under the impression we called it "Lexicon CSS" internally, but externally it should be "Lexicon". 

/cc @robert-frampton

**Comment by blzaugg** [comment]
https://github.com/sez11a/liferay-docs/pull/2539#issuecomment-331152344

**Comment by mwilliams2014** [comment]
sent https://github.com/sez11a/liferay-docs/pull/2547

**Pull request merged**
