### PR TITLE
Update 01-creating-a-soy-portlet.markdown

### PR DESCRIPTION
**Pull request by alexweirig**
@Reference annotation currently still not supported by Liferay IDE. Annotation has to be set on the setter method

### CODE REVIEW

**Comment by mwilliams2014** [comment]
Thanks @alexweirig ! This code is not needed and is being removed. See https://issues.liferay.com/browse/LPS-70144 to track.

**Comment by mwilliams2014** [comment]
@alexweirig @Reference annotation should be supported in Liferay IDE, as that is considered best practice. I've filed a bug here: https://issues.liferay.com/browse/IDE-3087.

What version of IDE are you using?

**Comment by mwilliams2014** [comment]
@alexweirig The current version of IDE's project templates right now (blade 2.0.1) uses the older OSGi 5.0.0 spec, which means @Reference can only be added to methods not fields. In the upcoming blade release (2.0.2) the templates have been updated to support OSGi 6.

If you're using Liferay IDE make sure the project created has the OSGi level 6 annotations.

For now, you can configure your maven/gradle project right now with OSGi 6 spec libraries in the build.gradle or pom.xml and then the @Reference annotation will work as expected.

**Comment by alexweirig** [comment]
@mwilliams2014 We were using the M1 stable build for those tests.

**Comment by mwilliams2014** [comment]
OSGi 6 will be supported in the next release of blade. For now you should be able to manually configure your project to use the level 6 annotations. Please let me know if you have any problems. thx!

**Comment by alexweirig** [comment]
@mwilliams2014 sure that works for me.
Thanks

**Comment by sez11a** [comment]
This was fixed in the product; thanks!

**Pull request closed without merging**
